site_name: MOCOCJ

nav:
  - Home: index.md
  - Chrome Resources: assignment0.md
  - Conceptual Architecture: assignment1.md
  - Concrete Architecture: assignment2.md
  - Proposed Enhancement: assignment3.md